apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ahsouza-nginx

### 3 MAX PODS to Templates
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: ahsouza-nginx
    spec:
      ### Container NGINX + Alpine
      containers:
      - name: nginx
        image: nginx:1.17-alpine
        ports:
          - containerPort: 80
            name: http
            protocol: TCP
          - containerPort: 443
            name: https
            protocol: TCP
        resources:
          limits:
            cpu: 10m
            memory: 20Mi
          requests:
            cpu: 10m
            memory: 20Mi

        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: nginx-conf
          readOnly: true
      ### Volume Kubernets ConfigMap: Configurações NGINX    
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
          items:
            - key: nginx.conf
              path: nginx.conf